-- ============================================================
-- E-COMMERCE SQL DATA ANALYSIS
-- Portfolio Project
-- Database: MySQL
-- ============================================================

-- ============================================================
-- 1. BASIC DATASET OVERVIEW
-- ============================================================

-- How many customers are there?
SELECT COUNT(*) AS total_customers
FROM customers;

-- How many orders were placed?
SELECT COUNT(*) AS total_orders
FROM orders;

-- What are the different product categories?
SELECT DISTINCT category
FROM products;

-- What are the top 10 most expensive products?
SELECT product_name, price
FROM products
ORDER BY price DESC
LIMIT 10;

-- What is the average product price?
SELECT ROUND(AVG(price), 2) AS average_price
FROM products;


-- ============================================================
-- 2. ORDER ANALYSIS
-- ============================================================

-- How many orders are completed / cancelled / pending?
SELECT status, COUNT(*) AS total_orders
FROM orders
GROUP BY status;

-- Which cities have the most customers?
SELECT city, COUNT(*) AS customer_count
FROM customers
GROUP BY city
ORDER BY customer_count DESC
LIMIT 1;

-- How many products are there in each category?
SELECT category, COUNT(*) AS products_count
FROM products
GROUP BY category;

-- What is the average product price for each category?
SELECT category, ROUND(AVG(price), 2) AS avg_price
FROM products
GROUP BY category;

-- Which category has the highest number of products?
SELECT category, COUNT(*) AS total_products
FROM products
GROUP BY category
ORDER BY total_products DESC
LIMIT 1;


-- ============================================================
-- 3. CUSTOMER + ORDER JOINS
-- ============================================================

-- Display customers with their orders.
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    o.order_id,
    o.status
FROM customers AS c
INNER JOIN orders AS o
    ON c.customer_id = o.customer_id
ORDER BY c.customer_id;

-- How many orders has each customer placed?
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    COUNT(o.order_id) AS total_orders
FROM customers AS c
INNER JOIN orders AS o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY total_orders DESC;

-- Which customer has placed the highest number of orders?
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    COUNT(o.order_id) AS total_orders
FROM customers AS c
INNER JOIN orders AS o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY total_orders DESC
LIMIT 1;

-- Order date along with customer name and city.
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    c.city,
    o.order_date
FROM customers AS c
INNER JOIN orders AS o
    ON c.customer_id = o.customer_id
ORDER BY c.customer_id, o.order_date;


-- ============================================================
-- 4. CUSTOMER REVENUE ANALYSIS
-- ============================================================

-- Revenue generated by each customer.
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS revenue
FROM customers AS c
INNER JOIN orders AS o
    ON c.customer_id = o.customer_id
INNER JOIN order_items AS oi
    ON o.order_id = oi.order_id
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY revenue DESC;

-- Top 10 customers by total spending.
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS revenue
FROM customers AS c
INNER JOIN orders AS o
    ON c.customer_id = o.customer_id
INNER JOIN order_items AS oi
    ON o.order_id = oi.order_id
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY revenue DESC
LIMIT 10;


-- ============================================================
-- 5. PRODUCT PERFORMANCE
-- ============================================================

-- Top 10 best-selling products by quantity.
SELECT
    p.product_id,
    p.product_name,
    SUM(oi.quantity) AS total_quantity_sold
FROM order_items AS oi
INNER JOIN products AS p
    ON oi.product_id = p.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_quantity_sold DESC
LIMIT 10;

-- Top 10 products by revenue.
SELECT
    p.product_id,
    p.product_name,
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS revenue
FROM order_items AS oi
INNER JOIN products AS p
    ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name
ORDER BY revenue DESC
LIMIT 10;

-- Which products have never been ordered?
SELECT
    p.product_id,
    p.product_name
FROM products AS p
LEFT JOIN order_items AS oi
    ON p.product_id = oi.product_id
WHERE oi.product_id IS NULL;

-- Which product category generates the highest total revenue?
SELECT
    p.category,
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS revenue
FROM order_items AS oi
INNER JOIN products AS p
    ON p.product_id = oi.product_id
GROUP BY p.category
ORDER BY revenue DESC
LIMIT 1;


-- ============================================================
-- 6. CITY + REVENUE ANALYSIS
-- ============================================================

-- Orders by city.
SELECT
    c.city,
    COUNT(o.order_id) AS orders_in_city
FROM customers AS c
INNER JOIN orders AS o
    ON o.customer_id = c.customer_id
GROUP BY c.city
ORDER BY orders_in_city DESC;

-- Which cities generate the highest total revenue?
SELECT
    c.city,
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS revenue
FROM customers AS c
INNER JOIN orders AS o
    ON o.customer_id = c.customer_id
INNER JOIN order_items AS oi
    ON o.order_id = oi.order_id
GROUP BY c.city
ORDER BY revenue DESC;


-- ============================================================
-- 7. REVENUE KPIs
-- ============================================================

-- What is the total revenue from all orders?
SELECT
    ROUND(SUM(quantity * unit_price), 2) AS total_revenue
FROM order_items;

-- What is the average order value?
SELECT
    ROUND(
        SUM(oi.quantity * oi.unit_price)
        / COUNT(DISTINCT oi.order_id),
        2
    ) AS average_order_value
FROM order_items AS oi;


-- ============================================================
-- 8. TIME-BASED ANALYSIS
-- ============================================================

-- Which month generated the highest revenue?
-- YEAR is included so the same month across different years
-- is not incorrectly combined.
SELECT
    YEAR(o.order_date) AS order_year,
    MONTH(o.order_date) AS order_month,
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS revenue
FROM orders AS o
INNER JOIN order_items AS oi
    ON o.order_id = oi.order_id
GROUP BY YEAR(o.order_date), MONTH(o.order_date)
ORDER BY revenue DESC
LIMIT 1;

-- Which month had the highest number of orders?
SELECT
    YEAR(order_date) AS order_year,
    MONTH(order_date) AS order_month,
    COUNT(order_id) AS no_of_orders
FROM orders
GROUP BY YEAR(order_date), MONTH(order_date)
ORDER BY no_of_orders DESC
LIMIT 1;


-- ============================================================
-- 9. CUSTOMER BEHAVIOR
-- ============================================================

-- Which customers have never placed an order?
SELECT
    c.customer_id,
    c.first_name,
    c.last_name
FROM customers AS c
LEFT JOIN orders AS o
    ON o.customer_id = c.customer_id
WHERE o.customer_id IS NULL;

-- What percentage of customers have placed at least one order?
SELECT
    ROUND(
        COUNT(DISTINCT o.customer_id) * 100.0
        / COUNT(DISTINCT c.customer_id),
        2
    ) AS percentage_of_customers
FROM customers AS c
LEFT JOIN orders AS o
    ON o.customer_id = c.customer_id;

-- Which customers have placed more than 5 orders?
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    COUNT(o.order_id) AS orders_placed
FROM customers AS c
INNER JOIN orders AS o
    ON o.customer_id = c.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name
HAVING COUNT(o.order_id) > 5
ORDER BY orders_placed DESC;

-- Average order value for each customer.
SELECT
    o.customer_id,
    ROUND(
        SUM(oi.quantity * oi.unit_price)
        / COUNT(DISTINCT o.order_id),
        2
    ) AS avg_order_value
FROM orders AS o
INNER JOIN order_items AS oi
    ON oi.order_id = o.order_id
GROUP BY o.customer_id
ORDER BY avg_order_value DESC;

-- Average number of items purchased per order.
SELECT
    ROUND(
        SUM(quantity) / COUNT(DISTINCT order_id),
        2
    ) AS avg_items_per_order
FROM order_items;

-- Top 10 customers by number of items purchased.
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    SUM(oi.quantity) AS no_of_items
FROM customers AS c
INNER JOIN orders AS o
    ON o.customer_id = c.customer_id
INNER JOIN order_items AS oi
    ON o.order_id = oi.order_id
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY no_of_items DESC
LIMIT 10;


-- ============================================================
-- 10. ADVANCED CUSTOMER ANALYSIS
-- ============================================================

-- Customers who spent more than the average customer spending.
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS spending
FROM customers AS c
INNER JOIN orders AS o
    ON c.customer_id = o.customer_id
INNER JOIN order_items AS oi
    ON o.order_id = oi.order_id
GROUP BY c.customer_id, c.first_name, c.last_name
HAVING SUM(oi.quantity * oi.unit_price) >
(
    SELECT AVG(total_spending)
    FROM
    (
        SELECT
            o.customer_id,
            SUM(oi.quantity * oi.unit_price) AS total_spending
        FROM orders AS o
        INNER JOIN order_items AS oi
            ON o.order_id = oi.order_id
        GROUP BY o.customer_id
    ) AS customer_spending
)
ORDER BY spending DESC;

-- Customers who placed orders but never purchased Electronics.
SELECT
    c.customer_id,
    c.first_name,
    c.last_name
FROM customers AS c
INNER JOIN orders AS o
    ON o.customer_id = c.customer_id
INNER JOIN order_items AS oi
    ON oi.order_id = o.order_id
INNER JOIN products AS p
    ON p.product_id = oi.product_id
GROUP BY c.customer_id, c.first_name, c.last_name
HAVING SUM(p.category = 'Electronics') = 0;


-- ============================================================
-- 11. TOP 10 CUSTOMER REVENUE CONTRIBUTION
-- ============================================================

-- What percentage of total revenue comes from the top 10 customers?
SELECT
    ROUND(
        SUM(top10.revenue)
        / (SELECT SUM(quantity * unit_price) FROM order_items)
        * 100,
        2
    ) AS top_10_revenue_percentage
FROM
(
    SELECT
        c.customer_id,
        ROUND(SUM(oi.quantity * oi.unit_price), 2) AS revenue
    FROM customers AS c
    INNER JOIN orders AS o
        ON o.customer_id = c.customer_id
    INNER JOIN order_items AS oi
        ON o.order_id = oi.order_id
    GROUP BY c.customer_id
    ORDER BY revenue DESC
    LIMIT 10
) AS top10;


-- ============================================================
-- END OF PROJECT
-- ============================================================
